admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    type: sonata_admin
    prefix: "/admin"

sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: "/admin"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: "/{_locale}"

fos_user_security_logout:
    path: "/logout"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/{_locale}/resetting"