services:
      AdminBundle\Security\Voter\UserVoter:
          tags:
              - { name: security.voter }

      AdminBundle\Security\Voter\ConfigVoter:
          tags:
              - { name: security.voter }