security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                target: homepage
            anonymous:    true
    access_control:
        - { path: ^/wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SONATA_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
        ROLE_SONATA_ADMIN_USER_READER:   [ROLE_SONATA_ADMIN_USER_LIST, ROLE_SONATA_ADMIN_USER_VIEW]
        ROLE_SONATA_ADMIN_USER_EDITOR:   [ROLE_SONATA_ADMIN_USER_CREATE, ROLE_SONATA_ADMIN_USER_EDIT]
        ROLE_SONATA_ADMIN_USER_ADMIN:    [ROLE_SONATA_ADMIN_USER_DELETE, ROLE_SONATA_ADMIN_USER_EXPORT]
        ROLE_SONATA_ADMIN_SITE_READER:
            - ROLE_SONATA_ADMIN_SITE_GROUP_LIST
            - ROLE_SONATA_ADMIN_SITE_GROUP_VIEW
            - ROLE_SONATA_ADMIN_SITE_LIST
            - ROLE_SONATA_ADMIN_SITE_VIEW
        ROLE_SONATA_ADMIN_SITE_EDITOR:
            - ROLE_SONATA_ADMIN_SITE_CREATE
            - ROLE_SONATA_ADMIN_SITE_EDIT
            - ROLE_SONATA_ADMIN_SITE_GROUP_CREATE
            - ROLE_SONATA_ADMIN_SITE_GROUP_EDIT
        ROLE_SONATA_ADMIN_SITE_ADMIN:
            - ROLE_SONATA_ADMIN_SITE_DELETE
            - ROLE_SONATA_ADMIN_SITE_EXPORT
            - ROLE_SONATA_ADMIN_SITE_GROUP_DELETE
            - ROLE_SONATA_ADMIN_SITE_GROUP_EXPORT
        ROLE_SONATA_ADMIN_CONTENT_READER:
            - ROLE_SONATA_ADMIN_CMS_PAGE_LIST
            - ROLE_SONATA_ADMIN_CMS_PAGE_VIEW
            - ROLE_SONATA_ADMIN_GALLERY_LIST
            - ROLE_SONATA_ADMIN_GALLERY_VIEW
        ROLE_SONATA_ADMIN_CONTENT_EDITOR:
            - ROLE_SONATA_ADMIN_CMS_PAGE_CREATE
            - ROLE_SONATA_ADMIN_CMS_PAGE_EDIT
            - ROLE_SONATA_ADMIN_GALLERY_CREATE
            - ROLE_SONATA_ADMIN_GALLERY_EDIT
            - ROLE_SONATA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_ADMIN_MEDIA_EDIT
        ROLE_SONATA_ADMIN_CONTENT_ADMIN:
            - ROLE_SONATA_ADMIN_CMS_PAGE_DELETE
            - ROLE_SONATA_ADMIN_CMS_PAGE_EXPORT
            - ROLE_SONATA_ADMIN_GALLERY_DELETE
            - ROLE_SONATA_ADMIN_GALLERY_EXPORT
            - ROLE_SONATA_ADMIN_MEDIA_DELETE
            - ROLE_SONATA_ADMIN_MEDIA_EXPORT
        ROLE_GUEST:
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_ADMIN_USER_READER
            - ROLE_SONATA_ADMIN_USER_EDIT
            - ROLE_SONATA_ADMIN_SITE_READER
            - ROLE_SONATA_ADMIN_CONTENT_READER
        ROLE_STAFF:
            - ROLE_GUEST
            - ROLE_SONATA_ADMIN_CONFIG_EDIT
            - ROLE_SONATA_ADMIN_CONTENT_EDITOR
        ROLE_ADMIN:
            - ROLE_STAFF
            - ROLE_SONATA_ADMIN_SITE_EDITOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SONATA_ADMIN_USER_ADMIN
            - ROLE_SONATA_ADMIN_SITE_ADMIN
            - ROLE_SONATA_ADMIN_CONTENT_ADMIN
    access_decision_manager:
        strategy: unanimous