imports:
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
