services:
    # EventListener

    FrontendBundle\Listener\EventListener\AlreadyVisitedEventListener:
        autowire: true
        lazy: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 8 }